In [5]:
# Define the documents as a dictionary where keys are document titles and values are document content
documents = {
    "Article: Pandas Basics": "This article covers the basics of using Pandas in Python.",
    "Tutorial: Data Visualization": "Learn about data visualization techniques with Python libraries.",
    "Case Study: Sales Analysis": "Analyze sales data using Python for a real-world case study."
}

In [57]:
# get the keys of the documents and store it in the list
key_documents = list(documents.keys())

# display the list of the key documents
key_documents

['Article: Pandas Basics',
 'Tutorial: Data Visualization',
 'Case Study: Sales Analysis']

In [56]:
# Extract the category of the key documents and store it 
for doc_categories in key_documents:
    documents_categories = [doc_categories.split(':')[0]]
    print(documents_categories)

['Article']
['Tutorial']
['Case Study']


In [53]:

# Extract the content values and put them in a list
document_content_list = list(documents.values())

# Display the list of document content
document_content_list

['This article covers the basics of using Pandas in Python.',
 'Learn about data visualization techniques with Python libraries.',
 'Analyze sales data using Python for a real-world case study.']

In [49]:
# Gather the set of all unique terms from the list content of document and diplay the result
unique_terms = {term for doc in document_content_list for term in doc.split()}
unique_terms

{'Analyze',
 'Learn',
 'Pandas',
 'Python',
 'Python.',
 'This',
 'a',
 'about',
 'article',
 'basics',
 'case',
 'covers',
 'data',
 'for',
 'in',
 'libraries.',
 'of',
 'real-world',
 'sales',
 'study.',
 'techniques',
 'the',
 'using',
 'visualization',
 'with'}

In [9]:
# create a matrix for the document by using the unique term
doc_term_matrix = {}

# your code here
for term in unique_terms:
    doc_term_matrix[term] = []
    
    for doc in document_content_list:
        if term in doc:
            doc_term_matrix[term].append(1)
        else: doc_term_matrix[term].append(0)

# display the result of the matrix
doc_term_matrix

{'data': [0, 1, 1],
 'with': [0, 1, 0],
 'basics': [1, 0, 0],
 'a': [1, 1, 1],
 'covers': [1, 0, 0],
 'Analyze': [0, 0, 1],
 'Python.': [1, 0, 0],
 'Pandas': [1, 0, 0],
 'case': [0, 0, 1],
 'of': [1, 0, 0],
 'article': [1, 0, 0],
 'This': [1, 0, 0],
 'libraries.': [0, 1, 0],
 'for': [0, 0, 1],
 'in': [1, 0, 1],
 'Learn': [0, 1, 0],
 'using': [1, 0, 1],
 'sales': [0, 0, 1],
 'Python': [1, 1, 1],
 'real-world': [0, 0, 1],
 'study.': [0, 0, 1],
 'the': [1, 0, 0],
 'visualization': [0, 1, 0],
 'techniques': [0, 1, 0],
 'about': [0, 1, 0]}

In [10]:
# import the numpy library if it doesn't work you need to install numpy
import numpy as np

docs_array = np.array(document_content_list, dtype='object')

v1 = np.array(doc_term_matrix['the'])    
v2 = np.array(doc_term_matrix['Python'])

print(v1)
print(v2)
print('-------')

# find the documents that have both terms from v1 and v2
v3 = v1 & v2

print(v3)

# display the content document from the result
[doc for doc in v3 * docs_array if doc]

[1 0 0]
[1 1 1]
-------
[1 0 0]


['This article covers the basics of using Pandas in Python.']

In [14]:
# find the document for those have at least one word
v1 = np.array(doc_term_matrix['the'])    
v2 = np.array(doc_term_matrix['Python'])

print(v1)
print(v2)
print('-------')
v3 = v1 | v2

print(v3)

[doc for doc in v3 * docs_array if doc]

[1 0 0]
[1 1 1]
-------
[1 1 1]


['This article covers the basics of using Pandas in Python.',
 'Learn about data visualization techniques with Python libraries.',
 'Analyze sales data using Python for a real-world case study.']

In [47]:
# read csv file 
import pandas as pd
df = pd.read_csv('tdoc.csv', header= None, names=['Title', 'Content'])
pd.options.display.colheader_justify="center"
df['Content'] = df['Content'].str.ljust(60)
print(df.to_string())

     Title                               Content                           
0  Document 1  This is the first document. It contains some words.         
1  Document 2  The second document is a bit longer and has different words.
2  Document 3  The third document is short. Short documents can be concise.


In [44]:
# dispale title & content
print('Title: \n')
list(df['Title'])

Title: 



['Document 1', 'Document 2', 'Document 3']

In [62]:
# extract category from title
for category in df['Title']:
    category = [category.split(' ')[0]]
    print(category)

['Document']
['Document']
['Document']


In [64]:
# extract key from title
for key_title in df['Title']:
    key_title = [key_title.split(' ')[1]]
    print(key_title)

['1']
['2']
['3']


In [43]:
#disply content
print('Contenet: \n')
list(df['Content'])

Contenet: 



['This is the first document. It contains some words.         ',
 'The second document is a bit longer and has different words.',
 'The third document is short. Short documents can be concise.']

In [59]:
# unique term
unique_terms = [term for doc in df['Content'] for term in doc.split()] 
unique_terms

['This',
 'is',
 'the',
 'first',
 'document.',
 'It',
 'contains',
 'some',
 'words.',
 'The',
 'second',
 'document',
 'is',
 'a',
 'bit',
 'longer',
 'and',
 'has',
 'different',
 'words.',
 'The',
 'third',
 'document',
 'is',
 'short.',
 'Short',
 'documents',
 'can',
 'be',
 'concise.']

In [72]:
# save to csv file
import pandas as pd
df = pd.DataFrame(unique_terms)
df.to_csv('tdoc1.csv', header=None, index=None)
